"""Init

Revision ID: 22d129e15e54
Revises: 
Create Date: 2023-06-10 09:41:49.970163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d129e15e54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinets',
    sa.Column('num_cabinet', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabinets_id'), 'cabinets', ['id'], unique=False)
    op.create_index(op.f('ix_cabinets_num_cabinet'), 'cabinets', ['num_cabinet'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('doors',
    sa.Column('door_num', sa.String(length=3), nullable=False),
    sa.Column('type_door', sa.String(length=10), nullable=True),
    sa.Column('cabinet_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doors_door_num'), 'doors', ['door_num'], unique=True)
    op.create_index(op.f('ix_doors_id'), 'doors', ['id'], unique=False)
    op.create_table('kid_groups',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('cabinet_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('cabinet_id > 0'),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kid_groups_id'), 'kid_groups', ['id'], unique=False)
    op.create_index(op.f('ix_kid_groups_name'), 'kid_groups', ['name'], unique=True)
    op.create_table('peoples',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('role_id > 0'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peoples_id'), 'peoples', ['id'], unique=False)
    op.create_index(op.f('ix_peoples_phone'), 'peoples', ['phone'], unique=True)
    op.create_table('readers',
    sa.Column('serial_num', sa.String(length=10), nullable=True),
    sa.Column('cabinet_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readers_id'), 'readers', ['id'], unique=False)
    op.create_index(op.f('ix_readers_serial_num'), 'readers', ['serial_num'], unique=True)
    op.create_table('cards',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('activate_date', sa.Date(), nullable=True),
    sa.Column('deactivate_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('deactivate_date > activate_date'),
    sa.CheckConstraint('people_id > 0'),
    sa.ForeignKeyConstraint(['people_id'], ['peoples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_code'), 'cards', ['code'], unique=True)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_table('childs',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('door_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('group_id > 0'),
    sa.ForeignKeyConstraint(['door_id'], ['doors.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['kid_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_childs_id'), 'childs', ['id'], unique=False)
    op.create_table('door_people',
    sa.Column('door_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('door_id > 0'),
    sa.CheckConstraint('people_id > 0'),
    sa.ForeignKeyConstraint(['door_id'], ['doors.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['peoples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_door_people_id'), 'door_people', ['id'], unique=False)
    op.create_table('group_people',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('group_id > 0'),
    sa.CheckConstraint('people_id > 0'),
    sa.ForeignKeyConstraint(['group_id'], ['kid_groups.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['peoples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_people_id'), 'group_people', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id_reader', sa.Integer(), nullable=True),
    sa.Column('id_card', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=6), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_card'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['id_reader'], ['readers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('people_child',
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('child_id > 0'),
    sa.CheckConstraint('people_id > 0'),
    sa.ForeignKeyConstraint(['child_id'], ['childs.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['peoples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_child_id'), 'people_child', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_child_id'), table_name='people_child')
    op.drop_table('people_child')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_group_people_id'), table_name='group_people')
    op.drop_table('group_people')
    op.drop_index(op.f('ix_door_people_id'), table_name='door_people')
    op.drop_table('door_people')
    op.drop_index(op.f('ix_childs_id'), table_name='childs')
    op.drop_table('childs')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_code'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_readers_serial_num'), table_name='readers')
    op.drop_index(op.f('ix_readers_id'), table_name='readers')
    op.drop_table('readers')
    op.drop_index(op.f('ix_peoples_phone'), table_name='peoples')
    op.drop_index(op.f('ix_peoples_id'), table_name='peoples')
    op.drop_table('peoples')
    op.drop_index(op.f('ix_kid_groups_name'), table_name='kid_groups')
    op.drop_index(op.f('ix_kid_groups_id'), table_name='kid_groups')
    op.drop_table('kid_groups')
    op.drop_index(op.f('ix_doors_id'), table_name='doors')
    op.drop_index(op.f('ix_doors_door_num'), table_name='doors')
    op.drop_table('doors')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_cabinets_num_cabinet'), table_name='cabinets')
    op.drop_index(op.f('ix_cabinets_id'), table_name='cabinets')
    op.drop_table('cabinets')
    # ### end Alembic commands ###
